language: rust
sudo: false
matrix:
  include:
    - rust: 1.31.1
    - rust: 1.36.0
      env:
      - TEST_NOSTD=1
    - rust: stable
      env:
      - TEST_NOSTD=1
    - rust: beta
      env:
      - TEST_NOSTD=1
    - rust: nightly
      env:
      - TEST_NOSTD=1
branches:
  only:
    - master
script:
  - |
      ( [ -z "$TEST_NOSTD" ] || cargo test -v --no-default-features --tests --lib) &&
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      cargo test --verbose --release --features "$FEATURES"
