language: rust

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5

os:
  - linux

rust:
  - 1.36.0
  - stable

env:
  - LLVM_VERSION=3.5 CLANG_VERSION=clang_3_5
  - LLVM_VERSION=7.0 CLANG_VERSION=clang_7_0

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.llvm

before_install: . ./ci/before_install.sh

script: . ./ci/script.sh
