variables:
  clippy_toolchain: 1.39.0
  minimum_toolchain: 1.39.0

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/resources
      endpoint: ctz

jobs:
- template: admin/pipelines/clippy.yml
  parameters:
    rustup_toolchain: ${{ variables.clippy_toolchain }}
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - template: admin/pipelines/rustup.yml
    - template: admin/pipelines/cargo-steps.yml
- job: MacOS
  pool:
    vmImage: macOS-10.13
  steps:
    - template: admin/pipelines/rustup.yml
    - template: admin/pipelines/cargo-steps.yml
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      stable:
        rustup_toolchain: stable
      beta:
        rustup_toolchain: beta
      nightly:
        rustup_toolchain: nightly
      minimum:
        rustup_toolchain: ${{ variables.minimum_toolchain }}
  steps:
    - template: admin/pipelines/rustup.yml
      parameters:
        rustup_toolchain: $(rustup_toolchain)
    - template: admin/pipelines/cargo-steps.yml
