variables:
  clippy_toolchain: 1.39.0
  minimum_toolchain: 1.39.0

jobs:
- template: admin/pipelines/clippy.yml
  parameters:
    rustup_toolchain: ${{ variables.clippy_toolchain }}
- job: Windows
  pool:
    vmImage: windows-2019
  steps:
    - template: admin/pipelines/rustup.yml
    - template: admin/pipelines/cargo-steps.yml
- job: MacOS
  pool:
    vmImage: macOS-10.15
  steps:
    - template: admin/pipelines/rustup.yml
    - template: admin/pipelines/cargo-steps.yml
    - template: admin/pipelines/macos-tests.yml
- job: Linux
  pool:
    vmImage: ubuntu-18.04
  strategy:
    matrix:
      stable:
        rustup_toolchain: stable
      beta:
        rustup_toolchain: beta
      nightly:
        rustup_toolchain: nightly
      minimum:
        rustup_toolchain: ${{ variables.minimum_toolchain }}
  steps:
    - template: admin/pipelines/rustup.yml
      parameters:
        rustup_toolchain: $(rustup_toolchain)
    - template: admin/pipelines/cargo-steps.yml
