language: rust

os:
  - linux
  - osx

rust:
  - stable

cache:
  directories:
    - $HOME/.cargo

script:
  - cargo build --all
  - cargo test
  - cargo test --no-default-features
  - cargo doc --all --no-deps