language: rust
sudo: false

matrix:
  include:
    - rust: 1.29.0
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      env:
       - FEATURES='nightly'

    # test a target without sse2 for raw/generic.rs
    - rust: stable
      env:
       - TARGET=i586-unknown-linux-gnu
      addons:
        apt:
          packages:
            - gcc-multilib
      install:
       - rustup target add $TARGET
      script:
       - cargo build --verbose --target $TARGET
       - cargo test --verbose --target $TARGET

branches:
  # Don't build these branches
  except:
    # Used by bors
    - trying.tmp
    - staging.tmp

before_script:
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then rustup component add rustfmt; fi

script:
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then cargo fmt -- --check; fi

  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo bench --verbose --features "$FEATURES"; fi
  - cargo doc --verbose --features "$FEATURES"

  - cargo build --verbose --features "$FEATURES serde"
  - cargo test --verbose --features "$FEATURES serde"
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo bench --verbose --features "$FEATURES serde"; fi
  - cargo doc --verbose --features "$FEATURES serde"
