language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - rust: 1.32.0
before_script: |
  set -e
  if [[ $TRAVIS_RUST_VERSION = 'stable' ]]; then
    rustup component add rustfmt clippy
  fi
script: |
  set -e
  cargo build
  cargo test
  ci/check-no-std.sh
  cargo test --all-features
  if [[ $TRAVIS_RUST_VERSION = 'stable' ]]; then
    cargo fmt --all -- --check
    cargo clippy --all-targets --all-features -- -D warnings
  fi
