language: rust

matrix:
  include:
    - rust: "nightly"
    - rust: "beta"
    - rust: "stable"
    - rust: "1.32.0"

script:
  - cargo build --verbose
  - cargo build --verbose --no-default-features
  - cargo test --verbose
  - cargo test --verbose --no-default-features
