language: rust
rust:
  - stable
  - beta

script:
  - cargo test
  - cargo test --release

matrix:
  include:
  - rust: stable
    script:
    - cargo test --no-default-features
    - cargo test --no-default-features --release
  - rust: 1.24.1
    script:
    - mv Cargo.lock.min Cargo.lock
    - cargo build
