language: rust
os:
  - linux
  - osx
  - windows
rust:
  - beta
  - stable
  - 1.13.0
matrix:
  exclude:
    # https://github.com/rust-lang/rust/issues/34674
    - os: osx
      rust: 1.13.0
  include:
    # WASI is only supported on nightly as it uses the #[thread_local] attribute
    - rust: nightly
      install:
        - curl https://wasmtime.dev/install.sh -sSf | bash
        - rustup target add wasm32-wasi
      script: >
          CARGO_TARGET_WASM32_WASI_RUNNER=$HOME/.wasmtime/bin/wasmtime
          cargo test --target wasm32-wasi
script:
  - cargo test
