language: rust

rust:
- stable
- beta
- nightly

script:
- cargo test --workspace
- cargo test --all-features
- cargo build --no-default-features
- cargo build --no-default-features --features alloc

matrix:
  include:
  - os: osx

  - name: cargo test --benches
    script:
    - cargo test --benches

  - name: docs.rs
    rust: nightly
    script:
    - RUSTDOCFLAGS='--cfg=docsrs -Dwarnings' cargo doc --all-features --no-deps

  - name: clippy
    install:
    - rustup component add clippy
    script:
    - cargo clippy --workspace --all-targets -- -D warnings
    - cargo clippy --workspace --all-targets --all-features -- -D warnings

  - name: cargo fmt
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt --all -- --check

branches:
  only:
  - staging
  - trying
  - master
