name: Upload documentation

on:
  push:
    branches:
      - master

jobs:
  upload_docs:
    name: Upload documentation
    runs-on: ubuntu-18.04
    if: github.repository == 'rust-lang/libc'

    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        run: TARGET=x86_64-unknown-linux-gnu sh ./ci/install-rust.sh
      - name: Generate documentation
        run: LIBC_CI=1 sh ci/dox.sh
      - name: Upload documentation to GitHub Pages
        uses: rust-lang/simpleinfra/github-actions/static-websites@master
        with:
          deploy_dir: target/doc
          github_token: "${{ secrets.GITHUB_TOKEN }}"
        if: github.ref == 'refs/heads/master'
